export const constants = {
    LIST_PRODUCT_NEW: "http://localhost:8080/api/v1/product/new",
    GET_PRODUCT_BY_ID: "http://localhost:8080/api/v1/product/",
    SAVE_PRODUCT:"http://localhost:8080/api/v1/product/admin/save",
    LOGIN: "http://localhost:8080/login",
    CATEGORY: "http://localhost:8080/api/v1/category",
    UPLOAD_PRODUCT_IMAGE:"http://localhost:8080/api/v1/product/admin/upload",
    UPLOAD_SUB_IMAGE:"http://localhost:8080/api/v1/admin/uploads/sub",
    GET_CART_ITEM_BY_USER: "http://localhost:8080/api/v1/cart/",
    ADD_CART_ITEM: "http://localhost:8080/api/v1/cart/add",
    LOGIN_GOOGLE_LINK: "https://accounts.google.com/o/oauth2/auth?scope=email%20profile%20openid&redirect_uri=http://localhost:8080/login/oauth2/code/google&response_type=code&client_id=866719052048-s4k9pnihvn9gp7rqfk66spf6bug0cnh2.apps.googleusercontent.com&approval_prompt=force",
    PAGE_ABLE_PRODUCT:"http://localhost:8080/api/v1/product/page/",
    PAGE_ABLE_PRODUCT_STOP:"http://localhost:8080/api/v1/product/stop/",
    DELETE_CART_ITEM:"http://localhost:8080/api/v1/cart/api/v1/cart/delete/",
    SIMILAR_PRODUCT_BY_CATEGORY_ID :"http://localhost:8080/api/v1/product/similar/category/",
    FIND_BY_KEY_WORD: "http://localhost:8080/api/v1/product/search?query=",
    GET_TOP_DISCOUNT_PRODUCT: "http://localhost:8080/api/v1/product/top-sale",
    CHECK_OUT:"http://localhost:8080/api/v1/order",
    GET_ORDERS_BY_CUSTOMER: "http://localhost:8080/api/v1/order/customer/all",
    ADMIN_MANAGE_ORDER: "http://localhost:8080/api/v1/order/admin/manage/order/",
    ADMIN_UPDATE_ORDER: "http://localhost:8080/api/v1/order/admin/updateOrder/",
    GET_PRODUCT_CUSTOM:"http://localhost:8080/api/v1/product/category/",
    CHECK_TOKEN:"http://localhost:8080/check/"
  } as const;
